.gitignore
data/cb-spider/log
data/cb-spider/meta_db
data/cb-tumblebug/log
data/cb-tumblebug/meta_db

Remove symbolic links

---

README.md

Update README.md for go get dependencies

Update README.md for go get dependencies

---

.gitignore
src/cmd/info.go
src/cmd/remove.go
src/cmd/run.go
src/cmd/stop.go
src/common/utility.go
src/main.go

| cb-operator command | [Docker Compose command](https://docs.docker.com/compose/reference/) | [Helm command](https://helm.sh/docs/helm/) |
|---|---|---|
| exec | exec | (no such command → not implemented) |
| info | ps + images | status + get pods |
| pull | pull | (no such command → not implemented) |
| remove | down | uninstall + (delete ns) + ? |
| run | up | create ns + install |
| stop | stop + ps | uninstall |
|   |   |   |
|   |   |   |

Add run, info, stop, and remove features for K8s mode

---

docker-compose-mode-files/conf/cb-spider/grpc_conf.yaml
docker-compose-mode-files/conf/cb-spider/log_conf.yaml
docker-compose-mode-files/conf/cb-spider/store_conf.yaml
docker-compose-mode-files/conf/cb-tumblebug/grpc_conf.yaml
docker-compose-mode-files/conf/cb-tumblebug/log_conf.yaml
docker-compose-mode-files/conf/cb-tumblebug/store_conf.yaml
docker-compose-mode-files/docker-compose.yaml
helm-chart/install/kubernetes/charts/cb-spider/Chart.yaml
helm-chart/install/kubernetes/charts/cb-tumblebug/Chart.yaml
helm-chart/install/kubernetes/charts/cb-tumblebug/values.yaml

[docker-compose-mode-files]
- Add `conf/cb-spider/*` (from https://github.com/cloud-barista/cb-spider/tree/master/conf)
- Add `conf/cb-tumblebug/*` (from https://github.com/cloud-barista/cb-tumblebug/tree/master/conf)
- Add mount point for `conf/` (in `docker-compose.yaml`)
- Update Spider and TB's image tag in `docker-compose.yaml`
- Update env vars in `docker-compose.yaml`
[helm-chart]
- Update Spider and TB's image tag in `charts/cb-spider/Chart.yaml` & `charts/cb-tumblebug/Chart.yaml`
- Update env vars in `charts/cb-tumblebug/values.yaml`

Update Spider and TB's image tag

---

src/cmd/info.go
src/cmd/pull.go
src/cmd/remove.go
src/cmd/run.go
src/cmd/stop.go
src/common/utility.go

ref #65 
- 모듈에 따른 Config file path 처리를 함수로 모듈화.
- 모든 명령어에 대해 적용.

Module CheckConfigPath and apply to all

---

docker-compose-mode-files/conf/cb-restapigw/apis/cb-restapigw-apis.yaml
docker-compose-mode-files/conf/cb-restapigw/cb-restapigw.yaml
docker-compose-mode-files/conf/cb-restapigw/store_conf.yaml
docker-compose-mode-files/docker-compose.yaml
helm-chart/charts/cb-restapigw/Chart.yaml
helm-chart/charts/cb-restapigw/files/conf/apis/cb-restapigw-apis.yaml
helm-chart/charts/cb-restapigw/files/conf/cb-restapigw.yaml
helm-chart/charts/cb-restapigw/files/conf/store_conf.yaml
helm-chart/charts/cb-restapigw/templates/configmap.yaml
helm-chart/charts/cb-restapigw/templates/deployment.yaml
helm-chart/charts/cb-restapigw/templates/service.yaml
helm-chart/charts/cb-restapigw/values.yaml
helm-chart/charts/cb-spider/Chart.yaml
helm-chart/charts/cb-tumblebug/Chart.yaml
helm-chart/charts/cb-webtool/Chart.yaml
helm-chart/values.yaml

- Resolves #73 
- Update container image tags
- `cb-spider:v0.2.0-20201025`
- `cb-tumblebug:v0.2.0-20201023`
- `cb-webtool:v0.2.0-20201020`
- `cb-restapigw:v0.2.0-20201022`

Update and add files of cb-restapigw

---

docker-compose-mode-files/conf/cb-dragonfly/config.yaml
docker-compose-mode-files/docker-compose.yaml

- docker-compose 업데이트
- CB-Dragonfly config.yaml 업데이트

CB-Dragonfly 프레임워크 에스프레소 버전 업데이트

---

docker-compose-mode-files/docker-compose.yaml
helm-chart/charts/cb-spider/Chart.yaml
helm-chart/charts/cb-tumblebug/Chart.yaml
helm-chart/charts/cb-webtool/Chart.yaml

Disable restart policies for DF components, and Update images tags

---

src/cmd/info.go
src/cmd/pull.go
src/cmd/remove.go
src/cmd/run.go
src/cmd/stop.go
src/common/utility.go

Change docker network name

---

helm-chart/charts/cb-ladybug/templates/deployment.yaml
helm-chart/charts/cb-spider/templates/deployment.yaml
helm-chart/charts/cb-tumblebug/templates/deployment.yaml

* deployment.yaml 에서 persistent.enabled 옵션 조건 추가
* deployment.yaml 에서 persistent.existingClaim 옵션 조건 추가
* CB-Ladybug, CB-Spider, CB-Tumblebug
* #93

fix : helm chart persistence volume options not workring #93

---

docker-compose-mode-files/docker-compose-df-only.yaml
docker-compose-mode-files/docker-compose.yaml
helm-chart/charts/cb-dragonfly/Chart.yaml
helm-chart/charts/cb-ladybug/Chart.yaml
helm-chart/charts/cb-restapigw/Chart.yaml
helm-chart/charts/cb-spider/Chart.yaml
helm-chart/charts/cb-tumblebug/Chart.yaml
helm-chart/charts/cb-webtool/Chart.yaml

@inno-cloudbarista 
CB-Dragonfly image tag 를 `espresso-v0.1-kafka` 에서 `v0.2.8` 로 업데이트 했습니다.
문제가 없는지 확인 부탁드립니다.

Update docker-compose-df-only.yaml, and container image tags

---

.github/workflows/changelog.yml

- Related comment: https://github.com/cloud-barista/cb-operator/pull/100#discussion_r569138561

Update 'changelog' GitHub workflow

---

docker-compose-mode-files/conf/cb-dragonfly/config.yaml
helm-chart/charts/cb-dragonfly/files/conf/config.yaml
helm-chart/charts/cb-dragonfly/templates/service.yaml

- CC: @hyokyungk @inno-cloudbarista 
- Ref: https://drive.google.com/file/d/1QgI_dRAxtrimlCGhdezqX56vsV6Dop-X/view

Update CB-Dragonfly's config.yaml

---

docker-compose-mode-files/conf/cb-restapigw/apis/cb-restapigw-apis.yaml
docker-compose-mode-files/conf/cb-restapigw/apis/dev-test.yaml
docker-compose-mode-files/conf/cb-restapigw/apis/trace-test.yaml
docker-compose-mode-files/conf/cb-restapigw/cb-restapigw.yaml
docker-compose-mode-files/docker-compose.yaml
helm-chart/charts/cb-restapigw/files/conf/apis/cb-restapigw-apis.yaml
helm-chart/charts/cb-restapigw/files/conf/cb-restapigw.yaml

Update config files

---

docker-compose-mode-files/conf/cb-dragonfly/log_conf.yaml
docker-compose-mode-files/conf/cb-ladybug/log_conf.yaml
docker-compose-mode-files/conf/cb-restapigw/apis/cb-restapigw-apis.yaml
docker-compose-mode-files/conf/cb-restapigw/apis/dev-test.yaml
docker-compose-mode-files/conf/cb-restapigw/apis/trace-test.yaml
docker-compose-mode-files/conf/cb-restapigw/cb-restapigw.yaml
docker-compose-mode-files/conf/cb-spider/log_conf.yaml
docker-compose-mode-files/conf/cb-tumblebug/log_conf.yaml
docker-compose-mode-files/data/grafana/data/dashboards/cb-restapigw-dashboard.json
docker-compose-mode-files/docker-compose.yaml
helm-chart/charts/cb-dragonfly/files/conf/log_conf.yaml
helm-chart/charts/cb-ladybug/files/conf/log_conf.yaml
helm-chart/charts/cb-restapigw/files/conf/apis/cb-restapigw-apis.yaml
helm-chart/charts/cb-restapigw/files/conf/cb-restapigw.yaml
helm-chart/charts/cb-spider/files/conf/log_conf.yaml
helm-chart/charts/cb-tumblebug/files/conf/log_conf.yaml

- `log_conf.yaml` 파일들 업데이트 (CC: @powerkimhub)
- As-is: `log/` 디렉토리가 `cb-spider/api-runtime/`, `cb-tumblebug/src/` 등에 생성됨
- To-be: `log/` 디렉토리가 `cb-spider/`, `cb-tumblebug/` 등에 생성됨
- 비고: `$CBMON_ROOT`, `$APP_ROOT` 에 해당하는 환경변수가 cb-restapigw, cb-webtool 에는 없음
- CB-Spider: `$CBSPIDER_ROOT`
- CB-Tumblebug: `$CBTUMBLEBUG_ROOT`
- CB-Ladybug: `$APP_ROOT`
- CB-Dragonfly: `$CBMON_ROOT`
- Cloud-Barista 프레임워크 컨테이너 이미지 태그 업데이트
- cb-restapigw conf file 변경사항 반영
- Docker Compose 모드에서, `meta_db` 볼륨 마운트 경로 수정
- As-is: `./data/cb-spider/meta_db:/root/go/src/github.com/cloud-barista/cb-spider/meta_db/dat`
- To-be: `./data/cb-spider/meta_db/:/root/go/src/github.com/cloud-barista/cb-spider/meta_db/`

Update conf files

---

docker-compose-mode-files/data/grafana/data/plugins/natel-plotly-panel/README.md
docker-compose-mode-files/docker-compose.yaml
helm-chart/charts/cb-tumblebug/Chart.yaml
helm-chart/charts/cb-tumblebug/values.yaml

- Related issue: https://github.com/cloud-barista/cb-tumblebug/issues/535

Update docker-compose.yaml and Helm chart

---

docker-compose-mode-files/conf/cb-dragonfly/config.yaml
docker-compose-mode-files/conf/cb-dragonfly/log_conf.yaml

[CB-Dragonfly] CB-Dragonfly config 파일 수정사항 적용
- config.yaml 수정사항 적용
- log_conf.yaml 수정사항 적용

[CB-Dragonfly] CB-Dragonfly config 파일 수정사항 적용

---

src/cmd/info.go
src/cmd/pull.go
src/cmd/remove.go
src/cmd/run.go
src/cmd/stop.go
src/common/utility.go

Remove `sudo` from Docker Compose & K8s mode

---

docker-compose-mode-files/conf/cb-dragonfly/config.yaml
helm-chart/charts/cb-dragonfly/files/conf/config.yaml

- CB-Dragonfly FW config 파일 최신화
- collector_port 항목 삭제
- rpDuration, deploy_type 항목 추가

CB-Dragonfly FW config 파일 최신화

---

docker-compose-mode-files/docker-compose.yaml
helm-chart/charts/cb-spider/Chart.yaml
helm-chart/charts/cb-spider/values.yaml
helm-chart/templates/metric-server/components.yml
src/cmd/info.go
src/cmd/pull.go
src/cmd/remove.go
src/cmd/run.go
src/cmd/stop.go
src/cmd/update.go
src/common/utility.go

- Closes #149 
- `metrics-server` 컨테이너 이미지 버전을 `v0.5.0` 으로 업데이트
- `Sprintf` 도입

Add 'operator update' subcommand

---

docker-compose-mode-files/docker-compose.yaml
helm-chart/charts/cb-webtool/values.yaml

Fixes this issue:
> docker compose모드로, cb-operator를 설치하니, spider, tumblebug 등 패키지 설치는 전부되었는데 그 이후부터가 좀 막힙니다. web-tool로 보이는 1234포트에 접속하고자 하나 반응이 전혀없고, ...
> 
> admin/admin 해도 반응이 없다시네요

Update cb-webtool env vars

---

src/common/utility.go

#152 이슈에서 언급한 바와 같이, 변화하지 않는 값은 상수로 고쳤습니다.

change some variables to constant(#152)

---

.github/workflows/build-test.yaml

Fixes https://github.com/cloud-barista/cb-operator/pull/165#issuecomment-929738197
~Let's wait for whether the build test passes or not! 😊~

Fix build test workflow

---

docker-compose-mode-files/docker-compose-df-only.yaml

- CB-TB를 통한 CB-DF 테스트에 급하게 필요하여, 해당 파일에 대해서만 업데이트를 진행하였습니다.
#172 와 중복된 내용입니다.

Change docker compose df only image version

---

docker-compose-mode-files/conf/cb-dragonfly/config.yaml
docker-compose-mode-files/docker-compose-df-only.yaml
docker-compose-mode-files/docker-compose.yaml
helm-chart/charts/cb-dragonfly/Chart.yaml
helm-chart/charts/cb-dragonfly/files/conf/config.yaml
helm-chart/charts/cb-dragonfly/values.yaml

Update DF v0.4.4 Docker-compose & HelmChart Config

Update CB-Dragonfly Docker-compose & HelmChart config file

---

helm-chart/charts/cb-dragonfly/files/conf/config.yaml

Fix based on 
https://github.com/cloud-barista/cb-operator/pull/172#discussion_r755865452

Fix error in df config for helm chart

---

OWNERS
docker-compose-mode-files/docker-compose.yaml
helm-chart/charts/cb-dragonfly/Chart.yaml
helm-chart/charts/cb-mcks/Chart.yaml
helm-chart/charts/cb-spider/Chart.yaml
helm-chart/charts/cb-tumblebug/charts/cb-tumblebug-mapui/Chart.yaml

Resolves https://github.com/cloud-barista/cb-operator/pull/177#issuecomment-1091119306
Docker Compose 모드, K8s 모드에서 모든 파드가 실행되는 것을 확인했습니다.

Update CB container image tags

---

docker-compose-mode-files/conf/cb-dragonfly/config.yaml
helm-chart/charts/cb-dragonfly/files/conf/config.yaml

- DF 구동 설정파일 (config.yaml) 수정 (Helm, Compose)

Update CB-Dragonfly conf files

---

docker-compose-mode-files/docker-compose.yaml

Based on https://github.com/cloud-barista/cloud-barista/issues/41

Update docker-compose.yaml for v0.8.0

---

docker-compose-mode-files/docker-compose.yaml
helm-chart/Chart.yaml
helm-chart/charts/cb-spider/Chart.yaml
helm-chart/charts/cb-tumblebug/charts/cb-tumblebug-mapui/Chart.yaml

[Update docker-compose.yaml for 0.8.0](https://github.com/cloud-barista/cb-operator/commit/530cb9f99897282beed71193cc34a314f95a4431)
[Update Chart.yaml for 0.8.0](https://github.com/cloud-barista/cb-operator/commit/55c86faf79dc20b8bcf9749076fbe9626a66df56)
[Update Chart.yaml mapui 0.8.0](https://github.com/cloud-barista/cb-operator/commit/a03420397afcfa73d1f30683c18a9ce4d1a3d25c)
[Update Chart.yaml for spider 0.8.0](https://github.com/cloud-barista/cb-operator/commit/29fe799e207b4627b9fb5bab70f1582358a85382)

Staging 0.8.0
