docker-compose.yaml
[phpLiteAdmin]
- Provides control for all SQL files in `./data/cb-tumblebug/meta_db`
- Endpoint: http://{host}:2015/phpliteadmin.php
- Default password: `admin` (set in the Docker image `acttaiwan/phpliteadmin`)
=> Remove MySQL and replace phpMyAdmin with phpLiteAdmin in docker-compose.yaml

src/main.go
Related PR: #38 (which is discarded)
[Workflow]
1. User builds and executes `./operator`
2. `operator` checks if the file `./CB_OPERATOR_MODE` exists
- If exists:
- If `CB_OPERATOR_MODE` == `singlenode` → Docker Compose based
- If `CB_OPERATOR_MODE` == `k8scluster` → K8s + Helm based (To-be-developed feature)
- If not exists, or other than `singlenode` or `k8scluster`:
- Scanf
- `1`  → Set `CB_OPERATOR_MODE` to `singlenode` and continue
- `2`  → Set `CB_OPERATOR_MODE` to `k8scluster` and continue
- Other than `1` or `2` → Scanf again
```
❯ ./operator     
CB_OPERATOR_MODE file does not exist.
[Options]
1: Single-node version (Docker Compose based)
2: K8s-cluster version (requires a K8s cluster with Helm 3 enabled)
Choose 1 or 2: 3
You should choose between 1 and 2.
CB_OPERATOR_MODE file …
```
=> Add mode-selection feature

helm-chart/install/kubernetes/values.yaml
[유의사항]
기존에 이 Helm chart 로 Cloud-Barista 를 실행했던 적이 있는 컴퓨터 또는 K8s 클러스터에서는
이전에 `cb-dragonfly-etcd` 파드가 실행되면서 생성된 PV/PVC 를 삭제해야
새로 실행하는 `cb-dragonfly-etcd` 파드가 정상적으로 동작합니다.
---
[원인 1]
- 이전에 etcd 3.4.9 가 실행되면서, PV+PVC가 생성되었고, etcd 3.4.9 가 여기에 내용을 기록했음
- 이후 etcd 버전을 3.3.11 로 바꿔서 실행하면, PV 의 내용을 읽어보는데, etcd 3.4 를 실행했을 때의 내용이 남아 있어서 에러 메시지를 출력하고 실행이 되지 않음
`kubectl logs cb-dragonfly-etcd-0 -n cloud-barista`
```
2020-07-30 06:33:10.549626 I | etcdserver: starting server... [version: 3.3.11, cluster version: to_be_decided]
2020-07-30 06:33:10.550567 I | etcdserver/membership: added member 2b96115f7d46bf19 [http://cb-dragonfly-etcd-0.cb-dragonfly-etcd-headless.cloud-barista.svc.cluster.local:2380] to cluster b1611160df1a5228
2020-07-30 06:33:10.550789 N | etcdserver/membership: set the initial cluster …
```
=> Change CB-Dragonfly's etcd version from 3.4.9 to 3.3.11

helm-chart/install/kubernetes/charts/cb-spider/templates/deployment.yaml, helm-chart/install/kubernetes/charts/cb-spider/templates/pvc.yaml, helm-chart/install/kubernetes/charts/cb-spider/values.yaml, helm-chart/install/kubernetes/charts/cb-tumblebug/templates/deployment.yaml, helm-chart/install/kubernetes/charts/cb-tumblebug/templates/pvc.yaml, helm-chart/install/kubernetes/charts/cb-tumblebug/values.yaml, helm-chart/install/kubernetes/values.yaml, src/cmd/remove.go
Tested with:
- `test/official/sequentialFullTest/testAll-mcis-mcir-ns-cloud.sh aws 1 jhseo`
- `test/official/sequentialFullTest/cleanAll-mcis-mcir-ns-cloud.sh aws 1 jhseo`
- Metadata of CB-Spider and CB-Tumblebug is preserved after `./operator stop` (`helm uninstall`) and `./operator run` (`helm install`)
---
| PV/PVC | Retain/Keep | Why "Yes"? |
|---|---|---|
| cb-spider | Yes | `"helm.sh/resource-policy": "keep"` |
| cb-tumblebug | Yes | `"helm.sh/resource-policy": "keep"` |
| data-cb-dragonfly-etcd-0 | Yes | PVC is generated through StatefulSets' dynamic volume provisioning. |
| cb-dragonfly-influxdb | No |   |
| cb-restapigw-influxdb | No |   |
| docker-registry | No |   |
|   |   |   |
|   |   |   |
---
[Below is For Your Information]
[When CB Helm chart is installed] (`./operator …
=> Add PVC for CB-Spider and CB-Tumblebug

helm-chart/install/kubernetes/charts/cb-spider/files/conf/grpc_conf.yaml, helm-chart/install/kubernetes/charts/cb-spider/files/conf/log_conf.yaml, helm-chart/install/kubernetes/charts/cb-spider/files/conf/store_conf.yaml, helm-chart/install/kubernetes/charts/cb-spider/templates/configmap.yaml, helm-chart/install/kubernetes/charts/cb-spider/templates/deployment.yaml, helm-chart/install/kubernetes/charts/cb-spider/values.yaml, helm-chart/install/kubernetes/charts/cb-tumblebug/files/conf/grpc_conf.yaml, helm-chart/install/kubernetes/charts/cb-tumblebug/files/conf/log_conf.yaml, helm-chart/install/kubernetes/charts/cb-tumblebug/files/conf/store_conf.yaml, helm-chart/install/kubernetes/charts/cb-tumblebug/templates/configmap.yaml, helm-chart/install/kubernetes/charts/cb-tumblebug/templates/deployment.yaml, helm-chart/install/kubernetes/charts/cb-tumblebug/values.yaml
[Config flow]
---
1. `*.yaml` files exist in
- `helm-chart/install/kubernetes/charts/cb-spider/files/conf/`
- `helm-chart/install/kubernetes/charts/cb-tumblebug/files/conf/`
---
2. In `helm-chart/install/kubernetes/charts/cb-spider/templates/configmap.yaml`
[Template]
```YAML
apiVersion: v1
kind: ConfigMap
metadata:
name: {{ include "cb-spider.fullname" . }}-config
labels:
{{- include "cb-spider.labels" .  | nindent 4 }}
data:
grpc_conf.yaml: |-
{{ range .Files.Lines "files/conf/grpc_conf.yaml" }}
{{ . }}
{{ end }}
log_conf.yaml: |-
{{ range .Files.Lines "files/conf/log_conf.yaml" }}
{{ . }}
{{ end }}
store_conf.yaml: |-
{{ range .Files.Lines "files/conf/store_conf.yaml" }}
{{ . }}
{{ end }}
```
[Will be rendered like this]
```YAML
apiVersion: v1
kind: ConfigMap
metadata:
name: …
```
=> Add Spider and TB's conf file to Helm chart

helm-chart/install/kubernetes/charts/cb-dragonfly/templates/deployment.yaml, helm-chart/install/kubernetes/charts/cb-dragonfly/templates/service.yaml, helm-chart/install/kubernetes/charts/cb-dragonfly/values.yaml, helm-chart/install/kubernetes/charts/cb-restapigw/templates/deployment.yaml, helm-chart/install/kubernetes/charts/cb-spider/templates/deployment.yaml, helm-chart/install/kubernetes/charts/cb-spider/templates/service.yaml, helm-chart/install/kubernetes/charts/cb-spider/values.yaml, helm-chart/install/kubernetes/charts/cb-tumblebug/templates/deployment.yaml, helm-chart/install/kubernetes/charts/cb-tumblebug/templates/service.yaml, helm-chart/install/kubernetes/charts/cb-tumblebug/values.yaml, helm-chart/install/kubernetes/charts/cb-webtool/templates/deployment.yaml, helm-chart/install/kubernetes/values.yaml
- NodePort ports are for expose-and-test for now.
|   | Container & Pod ports | K8s Svc ports | (K8s Ingress ...) |
|---|---|---|---|
| CB-Spider REST | 1024 | ClusterIP: 1024<br>NodePort: 31024 |   |
| CB-Spider gRPC | 50251 | ClusterIP: 50251<br>NodePort: 30251 |   |
| CB-Tumblebug REST | 1323 | ClusterIP: 1323<br>NodePort: 31323 |   |
| CB-Tumblebug gRPC | 50252 | ClusterIP: 50252<br>NodePort: 30252 |   |
| CB-Dragonfly REST | 9090 | ClusterIP: 9090<br>NodePort: 30090 |   |
| CB-Dragonfly gRPC | 50254 (TBD) | ClusterIP: 50254<br>NodePort: 30254 |   |
| CB-Dragonfly monitor | 8094/udp | ClusterIP: 8094<br>NodePort: 30094 |   |
| cb-webtool websvr | 1234 | ClusterIP: 1234<br>NodePort: 31234 |   |
| cb-restapigw endpoint | 8000 | ClusterIP: 8000<br>NodePort: 30080 |   |
| Docker Registry …
=> Open multiple ports for Spider, Tumblebug, and Dragonfly in Helm chart

src/cmd/run.go, src/common/utility.go
- 문제
f 옵션이 정상 동작하지 않음.
- 이유 
runCmd의 func init() 내부에 CB_OPERATOR_MODE  를 기준으로 -f 기본 값이 지정되도록 처리되어 있으나,
해당 시점에는 CB_OPERATOR_MODE  값이 정해지지 않으므로, 처리에 오류가 있었음.
```
switch common.CB_OPERATOR_MODE {
case common.Mode_DockerCompose:
pf.StringVarP(&common.FileStr, "file", "f", "../docker-compose-mode-files/docker-compose.yaml", "Path to Cloud-Barista Docker Compose YAML file")
case common.Mode_Kubernetes:
pf.StringVarP(&common.FileStr, "file", "f", "../helm-chart/values.yaml", "Path to Cloud-Barista Helm chart file")
default:
}
```
- 처리 방식
명령어 실행 시점에 -f 에 의한 config 를 모드에 따라 지정하도록 처리
=> Restore file parameter for Docker-compose

docker-compose-mode-files/conf/cb-spider/calllog_conf.yaml, docker-compose-mode-files/conf/cb-spider/cloudos.yaml, docker-compose-mode-files/conf/cb-spider/grpc_conf.yaml, docker-compose-mode-files/conf/cb-tumblebug/grpc_conf.yaml, docker-compose-mode-files/data/grafana/data/plugins/grafana-simple-json-datasource/src/partials/query.editor.html, docker-compose-mode-files/data/grafana/data/plugins/grafana-simple-json-datasource/src/plugin.json, docker-compose-mode-files/docker-compose.yaml, helm-chart/charts/cb-spider/files/conf/calllog_conf.yaml, helm-chart/charts/cb-spider/files/conf/cloudos.yaml, helm-chart/charts/cb-spider/files/conf/grpc_conf.yaml, helm-chart/charts/cb-spider/templates/service.yaml, helm-chart/charts/cb-spider/values.yaml, helm-chart/charts/cb-tumblebug/Chart.yaml, helm-chart/charts/cb-tumblebug/files/conf/grpc_conf.yaml, helm-chart/values.yaml
- (Resolves #55) Add files
- `docker-compose-mode-files/conf/cb-spider/calllog_conf.yaml`
- `docker-compose-mode-files/conf/cb-spider/cloudos.yaml`
- `helm-chart/charts/cb-spider/files/conf/calllog_conf.yaml`
- `helm-chart/charts/cb-spider/files/conf/cloudos.yaml`
- (Resolves #57) Update Spider's gRPC port from 50251 (30251 for NodePort) to 2048 (32048 for NodePort)
- Update CB-Tumblebug's container image tag
- `docker-compose-mode-files/docker-compose.yaml`
- `helm-chart/charts/cb-tumblebug/Chart.yaml`
=> Update docker-compose.yaml and Helm chart files

helm-chart/charts/cb-spider/templates/configmap.yaml
* CB-Spider configmap 에 "calllog_conf.yaml" 파일 추가 
* #90
=> fix : file  is missing on the helm chart #90

.github/workflows/build-on-pull-request.yml, .github/workflows/lint-on-push.yml, src/cmd/info.go, src/cmd/pull.go, src/cmd/remove.go, src/cmd/root.go, src/cmd/run.go, src/cmd/stop.go, src/common/utility.go, src/main.go
- (이 PR의 Reviewers 로 @hermitkim1 님도 추가하려고 했는데, 추가가 안 되네요.. :( )
- GitHub workflows 'lint' and 'build' YAML files by @hermitkim1
- https://github.com/hermitkim1/golang-ci-demo-by-github-actions#lint
- GitHub Lint action 실행 시 내부적으로 `golangci-lint` 가 실행되는데, `--out-format=github-actions` 옵션이 붙어서 실행되어,
GitHub 웹 인터페이스에서는 어느 파일의 어느 라인이 문제인지 알 수가 없습니다. [[링크]](https://github.com/jihoon-seo/cb-operator/runs/1642201369?check_suite_focus=true)
- 시도 1: 개발 VM에 `golint` 를 설치하고 실행하여 표시되는 사항들을 모두 수정했으나, GitHub Lint action 의 `golangci-lint` 는 여전히 에러가 1개 있다고 표시했습니다.
- 시도 2: 개발 VM에 `golangci-lint` 를 설치하고 실행하여 표시되는 사항들을 모두 수정했더니, GitHub Lint action 도 통과했습니다.
- 추가 시도: GitHub Lint action 실행 시 `--out-format=github-actions` 옵션을 뺄 수 있을까 했는데, `lint-on-push.yml` 파일에는 해당 구문이 없습니다.
=> Add GitHub workflows 'lint' and 'build'

.github/workflows/changelog.yml, CHANGELOG.md
- From [beego/.github/workflows/changelog.yml](https://github.com/beego/beego/blob/develop/.github/workflows/changelog.yml)
- PR 에 CHANGELOG 업데이트가 포함되어 있지 않으면 false 를 리턴하는 workflow 입니다.
- 필요 시 `Skip Changelog` 레이블을 달면 회피할 수 있습니다.
- [beego](https://github.com/beego/beego) repo 는 `master` 브랜치도 있지만 `develop` 브랜치를 default 브랜치로 사용하고 있습니다.
만약 저희도 이런 브랜칭 전략을 사용한다면,
`develop` 브랜치의 CHANGELOG 에는 거의 모든 PR에 대한 CHANGELOG 를 모으고,
나중에 `develop` 브랜치를 `master` 브랜치로 머지할 때 CHANGELOG 를 정리/정제/선별 하는 방안도 있겠습니다.
- 이것을 cb-operator 등에 도입해 보려고 하는 PR 입니다.
- 이렇게 누적된 CHANGELOG 를, 향후 릴리즈 시 마다 정리/정제/선별하여 기재하면 좋지 않을까 하여.. :)
=> Add changelog-check GitHub Actions workflow

docker-compose-mode-files/docker-compose.yaml
- TB -> Spider 호출 모드를 gRPC 에서 REST 로 변경했습니다.
- 각 FW가 다른 FW를 호출하는 REST API 주소를
api gw endpoint 에서
각 FW 의 endpoint 로 변경하여
각 FW가 다른 FW를 호출할 때 api gw 를 통하지 않고 직접 호출하도록 변경했습니다.
=> Disable calling-via-apigw and gRPC-calling

CHANGELOG.md, docker-compose-mode-files/conf/cb-dragonfly/log_conf.yaml, docker-compose-mode-files/conf/cb-ladybug/log_conf.yaml, docker-compose-mode-files/conf/cb-restapigw/log_conf.yaml, docker-compose-mode-files/conf/cb-tumblebug/log_conf.yaml, docker-compose-mode-files/docker-compose.yaml, helm-chart/charts/cb-dragonfly/files/conf/config.yaml, helm-chart/charts/cb-dragonfly/files/conf/log_conf.yaml, helm-chart/charts/cb-ladybug/files/conf/log_conf.yaml, helm-chart/charts/cb-restapigw/files/conf/log_conf.yaml, helm-chart/charts/cb-spider/Chart.yaml, helm-chart/charts/cb-tumblebug/Chart.yaml, helm-chart/charts/cb-tumblebug/files/conf/log_conf.yaml
- Remove CB-Dragonfly-related Docker network (Resolves #109)
- 각 프레임워크 별 cb-log 설정에 `logfile: false` 로 되어 있는 것을 `logfile: true` 로 변경했습니다.
- `helm-chart/charts/cb-dragonfly/files/conf/config.yaml` 파일의 `kafka:` 섹션에서
`deploy_type: "compose"` 로 되어 있는 것을 `deploy_type: "helm"` 으로 변경했습니다.
(`deploy environment "compose" => docker-compose or others , "helm" => helm chart on k8s`)
- docker-compose.yaml 과 Helm chart 에 있는 프레임워크 컨테이너 이미지 태그를 업데이트 했습니다.
- CB-Spider: `v0.3.2`
- CB-Tumblebug: `0.3.2`
- 관련 thread: https://github.com/cloud-barista/cb-tumblebug/discussions/411
=> Remove CB-Dragonfly-related Docker network

docker-compose-mode-files/data/grafana/data/plugins/briangann-gauge-panel/README.md, docker-compose-mode-files/docker-compose.yaml, helm-chart/charts/cb-dragonfly/Chart.yaml, helm-chart/charts/cb-restapigw/Chart.yaml, helm-chart/charts/cb-spider/Chart.yaml, helm-chart/charts/cb-spider/values.yaml, helm-chart/charts/cb-tumblebug/Chart.yaml
- 컨테이너 이미지 태그 업데이트
- 일부 CSP의 VM은 IPv6 을 지원하지 않아서
Docker Compose 모드로 실행 시 IPv6 관련 에러가 발생함.
- `docker-compose.yaml` 의 `ports:` 에 `0.0.0.0:` 을 추가하여 에러 회피
=> Update docker-compose.yaml and Helm chart

helm-chart/values.yaml
- Ref: https://kubernetes.io/ko/docs/concepts/storage/persistent-volumes/#%EC%A0%91%EA%B7%BC-%EB%AA%A8%EB%93%9C
- These volume plugins support `ReadWriteOnce` only:
- `AWSElasticBlockStore`
- `AzureDisk`
- `GCEPersistentDisk`
=> Modify PV access mode to ReadWriteOnce

CHANGELOG.md, docker-compose-mode-files/conf/cb-ladybug/log_conf.yaml, docker-compose-mode-files/conf/cb-restapigw/log_conf.yaml, docker-compose-mode-files/conf/cb-spider/log_conf.yaml, docker-compose-mode-files/conf/cb-tumblebug/log_conf.yaml, docker-compose-mode-files/data/grafana/data/plugins/grafana-clock-panel/README.md, docker-compose-mode-files/docker-compose.yaml, helm-chart/charts/cb-dragonfly/Chart.yaml, helm-chart/charts/cb-dragonfly/files/conf/config.yaml, helm-chart/charts/cb-dragonfly/files/conf/log_conf.yaml, helm-chart/charts/cb-ladybug/Chart.yaml, helm-chart/charts/cb-ladybug/files/conf/log_conf.yaml, helm-chart/charts/cb-restapigw/Chart.yaml, helm-chart/charts/cb-restapigw/files/conf/log_conf.yaml, helm-chart/charts/cb-spider/Chart.yaml, helm-chart/charts/cb-spider/files/conf/log_conf.yaml, helm-chart/charts/cb-tumblebug/Chart.yaml, helm-chart/charts/cb-tumblebug/files/conf/log_conf.yaml, helm-chart/charts/cb-tumblebug/values.yaml, helm-chart/charts/cb-webtool/Chart.yaml
- #130 (CB-Dragonfly config 파일 수정사항 적용) 변경사항을 Helm chart 에도 반영
- 로그 파일명을 `cblogs.log` 에서 각 프레임워크별로 다르게 설정
- 각 프레임워크별 최신 컨테이너 이미지 태그 반영
- https://hub.docker.com/r/cloudbaristaorg/cb-spider/tags?page=1&ordering=last_updated
- https://hub.docker.com/r/cloudbaristaorg/cb-tumblebug/tags?page=1&ordering=last_updated
- https://hub.docker.com/r/cloudbaristaorg/cb-ladybug/tags?page=1&ordering=last_updated
- https://hub.docker.com/r/cloudbaristaorg/cb-dragonfly/tags?page=1&ordering=last_updated
- https://hub.docker.com/r/cloudbaristaorg/cb-webtool/tags?page=1&ordering=last_updated
- https://hub.docker.com/r/cloudbaristaorg/cb-restapigw/tags?page=1&ordering=last_updated
- https://github.com/cloud-barista/cb-tumblebug/pull/616 (Move Swagger doc files) 으로 인한 변경사항 반영
=> Update conf files

docker-compose-mode-files/docker-compose-df-only.yaml, docker-compose-mode-files/docker-compose.yaml, helm-chart/charts/cb-dragonfly/files/conf/config.yaml, src/cmd/run.go
- cb-dragonfly-influxdb, cb-restapigw-influxdb 를 위해 노출했던 8083 포트를 8088 로 수정
(https://github.com/cloud-barista/cb-dragonfly/issues/71)
- `helm-chart/charts/cb-dragonfly/files/conf/config.yaml` 에서
`influxdb:` `external_port:` 를 `28086` 에서 `8086` 으로 변경
(https://github.com/cloud-barista/cb-operator/pull/131#issuecomment-866690901)
- Add support for GKE
- GCP 웹 콘솔에서 GKE 클러스터를 생성한 뒤
`./operator run` 실행하면 다음과 같은 에러 발생
- GKE 클러스터를 만들면 `metrics-server` 파드 및 관련 리소스가 기본적으로 생성되는데
Cloud-Barista Helm chart 에도 `metrics-server` 파드 및 관련 리소스가 정의되어 있어서
already exist 에러 발생
> ❯ ./operator run
> CB_OPERATOR_MODE: Kubernetes
> 
> [Setup and Run Cloud-Barista]
> 
> [Config path] ../helm-chart/values.yaml
> 
> namespace/cloud-barista configured
> install.go:159: [debug] Original chart version: ""
> …
=> Add support for GKE

docker-compose-mode-files/docker-compose.yaml, helm-chart/charts/cb-dragonfly/Chart.yaml, helm-chart/charts/cb-dragonfly/files/conf/config.yaml, helm-chart/charts/cb-dragonfly/values.yaml, helm-chart/charts/cb-ladybug/Chart.yaml, helm-chart/charts/cb-ladybug/values.yaml, helm-chart/charts/cb-restapigw/Chart.yaml, helm-chart/charts/cb-restapigw/values.yaml, helm-chart/charts/cb-spider/Chart.yaml, helm-chart/charts/cb-spider/templates/configmap.yaml, helm-chart/charts/cb-spider/values.yaml, helm-chart/charts/cb-tumblebug/Chart.yaml, helm-chart/charts/cb-tumblebug/values.yaml, helm-chart/charts/cb-webtool/values.yaml, helm-chart/values.yaml
- cb-store v0.4.1 반영된 각 FW 릴리즈의 컨테이너 이미지로 업데이트
- 관련 디스커션: https://github.com/cloud-barista/cb-operator/discussions/144
- CB-Spider ENV 변경사항 반영
- 관련 이슈: https://github.com/cloud-barista/cb-spider/issues/445
- 관련 위키: https://github.com/cloud-barista/cb-spider/wiki/CB-Spider-Service-Address-Configuration
- cb-dragonfly-kapacitor Pod/Svc의 name/fullname 변경
- 관련 커멘트: https://github.com/cloud-barista/cb-operator/pull/140#discussion_r671088138
- `name`: `cb-dragonfly-kapacitor` -> `dragonfly-kapacitor`
- `fullname`: `cloud-barista-cb-dragonfly-kapacitor` -> `cloud-barista-dragonfly-kapacitor`
- Helm chart 에서, `pullPolicy:`를 `IfNotPresent`에서 `Always`로 변경 (`appVersion`을 `latest`로 사용하는 경우를 대비)
- Helm chart 에서, prometheus, grafana, metricServer 재활성화
=> Update Helm chart and docker-compose.yaml

docker-compose-mode-files/conf/cb-ladybug/grpc_conf.yaml, docker-compose-mode-files/docker-compose.yaml, helm-chart/charts/cb-dragonfly/templates/deployment.yaml, helm-chart/charts/cb-ladybug/files/conf/grpc_conf.yaml, helm-chart/charts/cb-ladybug/templates/deployment.yaml, helm-chart/charts/cb-restapigw/templates/deployment.yaml, helm-chart/charts/cb-spider/Chart.yaml, helm-chart/charts/cb-spider/templates/deployment.yaml, helm-chart/charts/cb-tumblebug/templates/deployment.yaml, helm-chart/values.yaml
- Add initContainers to wait for etcd
- Related discussion: #144
- 적용 대상: etcd를 사용하는 CB FW 전부 (Spider, Tumblebug, Ladybug, Dragonfly, restapigw)
- CB-Ladybug에 추가된 `grpc_conf.yaml` 를 
Docker Compose files & Helm chart files 에 추가
- CB-Spider container image tag 업데이트
- etcd Helm chart 에 의해 실행되는 etcd의 RBAC Auth를 disable
- Closes #146
- cb-store에서 etcd auth 가 아직 구현되지 않았음 
(https://github.com/cloud-barista/cb-store/issues/21)
=> Add initContainers to wait for etcd

docker-compose-mode-files/docker-compose.yaml, helm-chart/charts/cb-dragonfly/templates/ingress.yaml, helm-chart/charts/cb-ladybug/templates/ingress.yaml, helm-chart/charts/cb-mcks/Chart.yaml, helm-chart/charts/cb-mcks/templates/ingress.yaml, helm-chart/charts/cb-restapigw-readonly/templates/ingress.yaml, helm-chart/charts/cb-restapigw/templates/ingress.yaml, helm-chart/charts/cb-spider/Chart.yaml, helm-chart/charts/cb-spider/templates/ingress.yaml, helm-chart/charts/cb-tumblebug/Chart.yaml, helm-chart/charts/cb-tumblebug/charts/cb-tumblebug-mapui/Chart.yaml, helm-chart/charts/cb-tumblebug/charts/cb-tumblebug-mapui/templates/ingress.yaml, helm-chart/charts/cb-tumblebug/templates/ingress.yaml, helm-chart/charts/cb-webtool/templates/ingress.yaml, helm-chart/templates/ingress/ingress.yaml, helm-chart/templates/metric-server/components.yml
- K8s v1.22 에서, `extensions/v1beta1`, `networking.k8s.io/v1beta1` 등의 K8s API가 deprecate 되었습니다. 
([관련 링크](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122))
- 이에, `*/v1beta1` API들을 `*/v1` API로 바꾸었습니다.
- 이 중, 예를 들어 `networking.k8s.io/v1` 은 `v1.19` 부터 제공되는 API 입니다.
따라서, 이 PR이 적용되면, CB Helm chart의 Required minimum K8s version은 `v1.19` 가 됩니다.
- Update Cloud-Barista container image tags
=> Update config files

helm-chart/charts/cb-spider/templates/horizontalpodautoscaler.yaml, src/cmd/run.go, src/cmd/update.go
- K8s v1.22, v1.23에서도 실행 가능하도록 autoscaling/v2 apiVersion을 autoscaling/v2beta2으로 하향
- AKS에 배포 시 metrics-server 배포하지 않도록 수정 (AKS 클러스터에는 기본적으로 제공됨)
=> Update CB Helm chart
